
import "./globals.css";
import React from 'react'
import { Montserrat } from "next/font/google";

import { App } from './App'
import { ProjectsProvider } from "context/ProjectsContext/ProjectsContext";
import { UserProvider } from '../context/UserContext/UserContext';



const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        <UserProvider>
          <ProjectsProvider>
            <App children={children}/>
          </ProjectsProvider>
        </UserProvider>
        
      </body>
    </html>
  );
}
